### ISSUE TITLE
Lewis_file abscence causes diffusion steady flame solver to fail to start.

### ISSUE THREAD

**Issue by wandadars** [LLNL/zero-rk#7]
diffusion_steady_flame_solver example fails to run because it can't find a Lewis_file.  I ran `bash run.sh` and got an error about the code not being able to located a Lewis file. So I looked in the other examples and found out that the Lewis file is named `Lewis_file`, so I created a blank file with that name, and the example started to run.

**Comment by whitesides1** [comment]
Thanks for reporting this issue.  There is a `Lewis_file` for that example [here](https://github.com/LLNL/zero-rk/blob/a01c180bf94d72fa021c309cb41a6f9fe1575752/examples/diffusion_steady_flame_solver/Lewis_file).  I think you may have gotten this error because you ran in the build directory instead of in the install directory.  Otherwise I would guess that some error happened during the install that prevented the Lewis file from being copied over.  Can you try (re-)running `make install` and check to see that the `Lewis_file` in the installed location matches the one from `<zerork_root>/examples/diffusion_steady_flame_solver`?

**Comment by whitesides1** [comment]
Closing due to lack of response.
